### ISSUE TITLE
Several questions about the release code.

### ISSUE THREAD

**Issue by jshilong** [CompVis/fm-boosting#6]
I would like to express my deepest gratitude for providing the community with such an invaluable codebase！ 

Over the past few weeks, I have been conducting a series of experiments leveraging your released code. However, I would appreciate your insights on several concerns that I have observed in my results.

Most notably, I attempted to train the model with 4x upsampling but found the results somewhat less satisfactory than expected. Specifically, I have been utilizing the inference function provided at https://github.com/CompVis/fm-boosting/blob/4e48b603a9b54efffe02e3461536b34b77967a9e/fmboost/trainer.py#L329C9-L329C27 for these experiments.

left is gt， middle is prediction， and right is input 
<img width="2037" alt="截屏2024-10-15 上午12 12 08" src="https://github.com/user-attachments/assets/59499361-192a-4005-9fed-d5d6a699a57c">

<img width="2032" alt="截屏2024-10-15 上午12 13 29" src="https://github.com/user-attachments/assets/f7d9e148-fef1-417b-97b8-064548ca9fd0">

We can see there are always artifacts in the model prediction.

Furthermore, I have noticed that sigma_min was defined as zero in the released code. I was wondering if you could shed some light on how this might impact the overall performance or the final results of the model.

Thank you in advance for your time and assistance！

**Comment by yangqianwann** [comment]
Hi, I have the same problem, do you solve this issue?

**Comment by benearnthof** [comment]
@jshilong could you also elaborate on which pretrained KLAutoencoder you used? The paper mentions Stable Diffusion 1.5 but the implementation in the paper has different names in the state dict than the one in the diffusers library, so I was wondering if there is a specific checkpoint that works out of the box?
